//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguagesSchool
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ClientService = new HashSet<ClientService>();
            this.ServicePhoto = new HashSet<ServicePhoto>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public decimal Cost { get; set; }
        public int DurationInSeconds { get; set; }
        public string Description { get; set; }
        public Nullable<double> Discount { get; set; }
        public string MainImagePath { get; set; }

        public float DurationInMinute
        {
            get
            {
                return DurationInSeconds / 60; ;
            }
        }
        public double CurrentPrice
        {
            get
            {
                if (Discount != null)
                {
                    return Convert.ToDouble(Cost) - (Convert.ToDouble(Cost) / 100 * Convert.ToDouble(Discount));
                }
                else
                {
                    return Convert.ToDouble(Cost);
                }
            }
        }
        public SolidColorBrush DiscountColor
        {
            get
            {
                if (Discount != null)
                {
                    SolidColorBrush withDis = new SolidColorBrush(Color.FromRgb(231, 250, 191));
                    return withDis;
                }
                else
                {
                    SolidColorBrush withoutDis = new SolidColorBrush(Color.FromRgb(255, 255, 255));
                    return withoutDis;
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePhoto> ServicePhoto { get; set; }
    }
}
